require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Metrics:
  Enabled: false

Style/Documentation:
   Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
