AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 100
